# Test configuration for conx CMDB
# This file is used for unit and integration tests

database:
  url: "postgres://cmdb_test:test_password@localhost:5433/cmdb_test"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "5m"

neo4j:
  url: "bolt://localhost:7688"
  username: "neo4j"
  password: "neo4j_test"
  max_pool_size: 10

redis:
  url: "redis://localhost:6380"
  pool_size: 5

jwt:
  secret: "test-secret-key-for-testing"
  access_token_ttl: "1h"
  refresh_token_ttl: "24h"

server:
  port: "8081"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "30s"

logging:
  level: "debug"
  format: "json"
  service: "api-test"

metrics:
  enabled: true
  path: "/metrics"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8081"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
  allow_credentials: true
